### ISSUE TITLE
Roles and Responsibilities for team 56

### ISSUE THREAD

**Issue by plaffyyy** [team-work-tools/team-work-telegram-bot#31]
https://github.com/plaffyyy @plaffyyy => Leader: Database Administration, GitHub Issues management, Bot Development (Python), Team Management, Research (Team Management Processes)

https://github.com/Danil0Danil @Danil0Danil => Project Documentation, Team Management, Research (similar applications)

https://github.com/essence-666 @againlose => DevOps, Bot Development, UI/UX (Bot), UI/UX (Mini App)

https://github.com/kibertod @CyberToad  => server admin, Bot Developer, Tech Part.

**Comment by deemp** [comment]
Superseded by https://github.com/team-work-tools/team-work-telegram-bot/issues/13
